backend:
  name: proxy
  proxy_url: https://punjabi-news-admin.pages.dev/api/github
  repo: rajvirsinghbenipal/hugo-content
  # IMPORTANT: Replace this with the branch you want to save to.
  branch: pre-release

media_folder: "assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    # IMPORTANT: Make sure this path exists in your content repo.
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}