backend:
  name: github
  repo: rajvir-cms-bot/hugo-content
  branch: main
  base_url: https://punjabi-news-admin.vercel.app
  auth_endpoint: /api/auth

# Using a minimal config to rule out any formatting errors
media_folder: "assets/uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}