backend:
  # Tells Decap to use our Vercel proxy
  name: proxy
  # The URL of our API function on Vercel
  proxy_url: https://punjabi-news-admin.vercel.app/api/github
  # The branch to save content to
  branch: pre-release

# The rest of your configuration is correct
media_folder: "assets/uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}